### ISSUE TITLE
`tiled` support

### ISSUE THREAD

**Issue by mrakitin** [xpdAcq/PDFstream#53]
We are observing an issue while running `pdfstream` in the [`2022-2.3-py38-tiled` conda environment](https://zenodo.org/record/6503107) with `tiled` and `databroker`>=2.0 at NSLS-II XPD:
```py
$ start_analysis_server
Traceback (most recent call last):
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/bin/run_server", line 10, in <module>
    sys.exit(run_server())
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/lib/python3.8/site-packages/pdfstream/main.py", line 71, in run_server
    fire.Fire(_run_server)
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/lib/python3.8/site-packages/pdfstream/main.py", line 56, in _run_server
    import pdfstream.servers.xpd_server as xpd_server
  File "/nsls2/conda/envs/2022-2.3-py38-tiled/lib/python3.8/site-packages/pdfstream/servers/xpd_server.py", line 4, in <module>
    import databroker.core
ModuleNotFoundError: No module named 'databroker.core'
```

Is there a plan to implement the support of `tiled` in this package?

**Comment by st3107** [comment]
I am doing that. I will make sure it is compatible with the tiled in the
version 0.6.1.

**Comment by mrakitin** [comment]
Thanks for the quick feedback, @st3107! Any idea when can we expect it?

**Comment by st3107** [comment]
I will do it this week. If this should be quick.

**Comment by st3107** [comment]
@mrakitin There is a bug about the `temp` in databroker. There is a PR to fix it but it hasn't been merged yet.

https://github.com/bluesky/databroker/pull/726

I need the temp db to test my software. Otherwise, I don't know if it works for the databroker or not. I will wait for the fix of the temp db and then do a test.

**Comment by mrakitin** [comment]
@st3107, the new version of databroker with the requested fix is ready (see https://github.com/conda-forge/databroker-feedstock/pull/44 for more details). Thanks!

**Comment by mrakitin** [comment]
bump

**Comment by st3107** [comment]
Thank you. I will check my software and make the update.

**Comment by mrakitin** [comment]
Thank you! @sghose asked about it yesterday.
